# Generated by Django 6.0.7 on 2026-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_latitude_alter_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=255),
            preserve_default=False,
        ),
    ]
