# Generated by Django 6.0.7 on 2026-07-15 13:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='layout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
