# Generated by Django 6.0.7 on 2026-07-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'verbose_name_plural': 'Patches'},
        ),
    ]
