# Generated by Django 6.0.7 on 2026-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
