# Generated by Django 6.0.7 on 2026-07-17 17:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_chore_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('description', models.TextField()),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.patch')),
            ],
        ),
    ]
