# Generated by Django 6.0.7 on 2026-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropHarvestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=255)),
                ('harvest_time', models.CharField(max_length=255)),
            ],
        ),
    ]
