# Generated by Django 6.0.7 on 2026-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cropharvesttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropharvesttime',
            name='id',
        ),
        migrations.AlterField(
            model_name='cropharvesttime',
            name='crop_type',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
