# Generated by Django 6.0.7 on 2026-07-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cropharvesttime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropharvesttime',
            name='harvest_time',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=255)),
                ('planted_date', models.DateField()),
                ('estimated_harvest_date', models.CharField(max_length=255)),
                ('number_planted', models.IntegerField(blank=True, null=True)),
                ('number_dead', models.IntegerField(default=0)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='app.patch')),
            ],
        ),
    ]
