# Generated by Django 6.0.7 on 2026-07-24 19:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cropharvesttime_harvest_time_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropharvesttime',
            name='crop_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='crop_photo'),
        ),
    ]
