# Generated by Django 6.0.7 on 2026-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cropharvesttime_crop_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_variety',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
