# Generated by Django 6.0.7 on 2026-08-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_harvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fequency', models.IntegerField()),
                ('last_watered_date', models.DateField(blank=True, null=True)),
                ('next_watering_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watering_schedule', to='app.patch')),
            ],
        ),
    ]
