# Generated by Django 6.0.7 on 2026-08-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wateringschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wateringschedule',
            old_name='fequency',
            new_name='frequency',
        ),
    ]
