# Generated by Django 6.0.7 on 2026-08-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_fequency_wateringschedule_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilisingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('last_fertilised_date', models.DateField(blank=True, null=True)),
                ('next_fertilising_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilising_schedule', to='app.patch')),
            ],
        ),
    ]
