# Generated by Django 6.0.7 on 2026-08-03 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fertilisingschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Plants', 'Plants'), ('Soil and Compost', 'Soil and Compost'), ('Fertilisers', 'Fertilisers'), ('Pesticides', 'Pesticides'), ('Pots and Containers', 'Pots and Containers'), ('Tools and Equipment', 'Tools and Equipment'), ('Other', 'Other')], max_length=255)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.patch')),
            ],
        ),
    ]
