# Generated by Django 6.0.7 on 2026-08-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_treatments', to='app.crop')),
            ],
        ),
    ]
