# Generated by Django 6.0.7 on 2026-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_diseasetreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetreatment',
            name='crop',
            field=models.CharField(max_length=255),
        ),
    ]
