# Generated by Django 6.0.7 on 2026-08-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_growingguide'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='growingguide',
            unique_together={('crop', 'city', 'country', 'latitude', 'longitude')},
        ),
    ]
