# Generated by Django 6.0.7 on 2026-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_growingguide_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
