# Generated by Django 6.0.7 on 2026-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_patch_patch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='patch',
            unique_together={('user', 'patch_name')},
        ),
    ]
