# Generated by Django 6.0.7 on 2026-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_patch_patch_name_alter_patch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growingguide',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=55.86515, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='growingguide',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-4.25763, max_digits=9),
            preserve_default=False,
        ),
    ]
