# Generated by Django 6.0.7 on 2026-08-22 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_crop_number_planted_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
