# Generated by Django 6.0.7 on 2026-08-22 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_harvest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilisingschedule',
            name='frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
